ALTER TABLE "ClBuilding" MODIFY
    "Section" NVARCHAR2(10);

ALTER TABLE "ClBuilding" MODIFY
    "Alley" NVARCHAR2(10);

ALTER TABLE "ClBuilding" MODIFY
    "Lane" NVARCHAR2(10);

ALTER TABLE "ClBuilding" MODIFY
    "Num" NVARCHAR2(10);

ALTER TABLE "ClBuilding" MODIFY
    "NumDash" NVARCHAR2(10);

ALTER TABLE "ClBuilding" MODIFY
    "Floor" NVARCHAR2(10);

ALTER TABLE "ClBuilding" MODIFY
    "FloorDash" NVARCHAR2(10);