CREATE TABLE "TfRcData" ( 
      LMSACN DECIMAL(7,0) DEFAULT 0 NOT NULL,
      LMSAPN DECIMAL(3,0) DEFAULT 0 NOT NULL,
      LMSASQ DECIMAL(3,0) DEFAULT 0 NOT NULL,
      TRXISD DECIMAL(8,0) DEFAULT 0 NOT NULL,
      FitRate DECIMAL(6,4) DEFAULT 0 NOT NULL,
)
;