--------------------------------------------------------
--  已建立檔案 - 星期四-五月-25-2023   
--------------------------------------------------------
DROP TABLE "FTP_USER";
--------------------------------------------------------
--  DDL for Table FTP_USER
--------------------------------------------------------

  CREATE TABLE "FTP_USER" 
   (	"USERID" VARCHAR2(64), 
	"USERPASSWORD" VARCHAR2(64), 
	"HOMEDIRECTORY" VARCHAR2(128), 
	"ENABLEFLAG" VARCHAR2(1) DEFAULT '1', 
	"WRITEPERMISSION" VARCHAR2(1) DEFAULT '0', 
	"IDLETIME" NUMBER(19,0) DEFAULT 0, 
	"UPLOADRATE" NUMBER(19,0) DEFAULT 0, 
	"DOWNLOADRATE" NUMBER(19,0) DEFAULT 0, 
	"MAXLOGINNUMBER" NUMBER(19,0) DEFAULT 0, 
	"MAXLOGINPERIP" NUMBER(19,0) DEFAULT 0
   ) ;
REM INSERTING into FTP_USER
SET DEFINE OFF;
Insert into FTP_USER (USERID,USERPASSWORD,HOMEDIRECTORY,ENABLEFLAG,WRITEPERMISSION,IDLETIME,UPLOADRATE,DOWNLOADRATE,MAXLOGINNUMBER,MAXLOGINPERIP) values ('DEV_ITX','1qaz2wsx','/home/weblogic/Dev/itxDoc/itxWrite/upload/FTP','Y','Y',3000,48000000,48000000,20,2);
Insert into FTP_USER (USERID,USERPASSWORD,HOMEDIRECTORY,ENABLEFLAG,WRITEPERMISSION,IDLETIME,UPLOADRATE,DOWNLOADRATE,MAXLOGINNUMBER,MAXLOGINPERIP) values ('SIT_ITX','1qaz2wsx','/home/weblogic/Sit/itxDoc/itxWrite/upload/FTP','Y','Y',3000,48000000,48000000,20,2);
Insert into FTP_USER (USERID,USERPASSWORD,HOMEDIRECTORY,ENABLEFLAG,WRITEPERMISSION,IDLETIME,UPLOADRATE,DOWNLOADRATE,MAXLOGINNUMBER,MAXLOGINPERIP) values ('SMS','1qaz2wsx','/home/weblogic/Sit/itxDoc/itxWrite/upload/FTP/SMS','Y','Y',3000,48000000,48000000,20,2);
Insert into FTP_USER (USERID,USERPASSWORD,HOMEDIRECTORY,ENABLEFLAG,WRITEPERMISSION,IDLETIME,UPLOADRATE,DOWNLOADRATE,MAXLOGINNUMBER,MAXLOGINPERIP) values ('UAT_ITX','1qaz2wsx','/home/weblogic/Uat/itxDoc/itxWrite/upload/FTP','Y','Y',3000,48000000,48000000,20,2);
Insert into FTP_USER (USERID,USERPASSWORD,HOMEDIRECTORY,ENABLEFLAG,WRITEPERMISSION,IDLETIME,UPLOADRATE,DOWNLOADRATE,MAXLOGINNUMBER,MAXLOGINPERIP) values ('PT1_ITX','1qaz2wsx','/home/weblogic/pt1/itxDoc/itxWrite/upload/FTP','Y','Y',3000,48000000,48000000,20,2);
Insert into FTP_USER (USERID,USERPASSWORD,HOMEDIRECTORY,ENABLEFLAG,WRITEPERMISSION,IDLETIME,UPLOADRATE,DOWNLOADRATE,MAXLOGINNUMBER,MAXLOGINPERIP) values ('PT2_ITX','1qaz2wsx','/home/weblogic/pt2/itxDoc/itxWrite/upload/FTP','Y','Y',3000,48000000,48000000,20,2);
--------------------------------------------------------
--  DDL for Index FTP_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FTP_USER_PK" ON "FTP_USER" ("USERID") 
  ;
--------------------------------------------------------
--  Constraints for Table FTP_USER
--------------------------------------------------------

  ALTER TABLE "FTP_USER" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "FTP_USER" MODIFY ("HOMEDIRECTORY" NOT NULL ENABLE);
  ALTER TABLE "FTP_USER" ADD CONSTRAINT "FTP_USER_PK" PRIMARY KEY ("USERID")
  USING INDEX  ENABLE;
