	UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L1001 顧客明細資料查詢]進入'
	WHERE "TranNo"='L1101';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L1001 顧客明細資料查詢]進入'
	WHERE "TranNo"='L1102';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L1001 顧客明細資料查詢]進入'
	WHERE "TranNo"='L1103';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L1001 顧客明細資料查詢]進入'
	WHERE "TranNo"='L1104';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L1905 顧客聯絡電話查詢]進入'
	WHERE "TranNo"='L1105';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L1907 公司戶財務報表查詢]進入'
	WHERE "TranNo"='L1107';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L1908 申請不列印書面通知書查詢]進入'
	WHERE "TranNo"='L1108';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2018共同借款人資料查詢]進入'
	WHERE "TranNo"='L291A';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2019合併額度控管資料查詢]進入'
	WHERE "TranNo"='L291B';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2035借款戶關係人/關係企業查詢]進入'
	WHERE "TranNo"='L2036';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2077清償作業明細資料查詢]進入'
	WHERE "TranNo"='L2076';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2001商品參數明細資料查詢]進入'
	WHERE "TranNo"='L2101';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2010申請案件明細資料查詢]進入'
	WHERE "TranNo"='L2111';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2018共同借款人資料查詢]進入'
	WHERE "TranNo"='L2118';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2019合併額度控管資料查詢]進入'
	WHERE "TranNo"='L2119';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2010申請案件明細資料查詢]進入'
	WHERE "TranNo"='L2151';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2010申請案件明細資料查詢]進入'
	WHERE "TranNo"='L2153';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2015額度明細資料查詢]進入'
	WHERE "TranNo"='L2154';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2021交易關係人查詢]進入'
	WHERE "TranNo"='L2221';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2022所有關係人資料查詢]進入'
	WHERE "TranNo"='L2222';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2020保證人明細資料查詢]進入'
	WHERE "TranNo"='L2250';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2035借款戶關係人/關係企業查詢]進入'
	WHERE "TranNo"='L2305';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2035借款戶關係人/關係企業查詢]進入'
	WHERE "TranNo"='L2306';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2038擔保品明細資料查詢]進入'
	WHERE "TranNo"='L2411';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2038擔保品明細資料查詢]進入'
	WHERE "TranNo"='L2412';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2038擔保品明細資料查詢]進入 '
	WHERE "TranNo"='L2413';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2038擔保品明細資料查詢]進入'
	WHERE "TranNo"='L2414';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2911不動產擔保品資料查詢]進入'
	WHERE "TranNo"='L2415';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2911不動產擔保品資料查詢]進入'
	WHERE "TranNo"='L2416';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2017額度與擔保品關聯查詢]進入'
	WHERE "TranNo"='L2417';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2918擔保品他項權利查詢]進入'
	WHERE "TranNo"='L2418';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2039擔保品重評明細資料查詢]進入'
	WHERE "TranNo"='L2480';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2060聯貸案訂約明細資料查詢]進入'
	WHERE "TranNo"='L2600';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2078法拍費用明細資料查詢]進入'
	WHERE "TranNo"='L2601';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2078法拍費用明細資料查詢]進入'
	WHERE "TranNo"='L2602';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2064企金費用明細資料查詢]進入'
	WHERE "TranNo"='L2604';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2077清償作業明細資料查詢]進入'
	WHERE "TranNo"='L2631';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2077清償作業明細資料查詢]進入'
	WHERE "TranNo"='L2632';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2061貸後契變手續費明細資料查詢(未入帳)]進入'
	WHERE "TranNo"='L2670';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2072顧客控管警訊明細資料查詢]進入'
	WHERE "TranNo"='L2702';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2073結清客戶申請個人資料控管查詢]進入'
	WHERE "TranNo"='L2703';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2921未齊件資料查詢]進入'
	WHERE "TranNo"='L2801';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2038擔保品明細資料查詢]進入'
	WHERE "TranNo"='L2911';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2038擔保品明細資料查詢]進入'
	WHERE "TranNo"='L2912';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2038擔保品明細資料查詢]進入'
	WHERE "TranNo"='L2913';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2038擔保品明細資料查詢]進入'
	WHERE "TranNo"='L2914';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2911不動產擔保品資料查詢]進入'
	WHERE "TranNo"='L2915';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L2911不動產擔保品資料查詢]進入'
	WHERE "TranNo"='L2916';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L3003預約撥款明細資料查詢]進入'
	WHERE "TranNo"='L3120';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L3004約定部分償還明細資料查詢]進入'
	WHERE "TranNo"='L3130';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L3005交易明細資料查詢]進入'
	WHERE "TranNo"='L3240';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L3005交易明細資料查詢]進入'
	WHERE "TranNo"='L3250';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L3072帳務備忘錄明細資料查詢]進入'
	WHERE "TranNo"='L3702';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L3074暫收款指定額度設定查詢]進入'
	WHERE "TranNo"='L3704';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L3932借戶利率查詢]進入'
	WHERE "TranNo"='L3721';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L3911繳息情形查詢]進入'
	WHERE "TranNo"='L3917';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L4002進入'
	WHERE "TranNo"='L420A';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L4002進入'
	WHERE "TranNo"='L420B';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易'
	WHERE "TranNo"='L4201';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易'
	WHERE "TranNo"='L4202';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易'
	WHERE "TranNo"='L4203';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易'
	WHERE "TranNo"='L4204';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L4920整批入帳明細查詢]進入'
	WHERE "TranNo"='L4205';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L4921進入'
	WHERE "TranNo"='L4210';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L4022地區利率查詢]進入'
	WHERE "TranNo"='L4322';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L4031進入'
	WHERE "TranNo"='L4325';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L4042進入'
	WHERE "TranNo"='L4410';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易： [L4043 郵局授權資料查詢]進入'
	WHERE "TranNo"='L4412';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L4943進入'
	WHERE "TranNo"='L4451';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L4951進入'
	WHERE "TranNo"='L4512';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L4060進入'
	WHERE "TranNo"='L4610';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L4960進入'
	WHERE "TranNo"='L4611';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L4922進入'
	WHERE "TranNo"='L4923';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L4926 匯款轉帳檔查詢]進入'
	WHERE "TranNo"='L4927';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L4031進入'
	WHERE "TranNo"='L4931';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L4042進入'
	WHERE "TranNo"='L4940';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='本交易為連動交易，不可直接進入'
	WHERE "TranNo"='L570A';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L5074債務協商作業－應處理事項清單]進入'
	WHERE "TranNo"='L597A';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L5901 資金運用概況查詢]進入'
	WHERE "TranNo"='L5101';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L5902進入'
	WHERE "TranNo"='L5102';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L5903 檔案借閱查詢]進入'
	WHERE "TranNo"='L5103';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L5905進入'
	WHERE "TranNo"='L5105';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L5907進入'
	WHERE "TranNo"='L5107';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L5906進入'
	WHERE "TranNo"='L5116';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L5021進入'
	WHERE "TranNo"='L5401';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L5024進入'
	WHERE "TranNo"='L5405';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L5023進入'
	WHERE "TranNo"='L5406';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L5022進入'
	WHERE "TranNo"='L5407';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L5051連動進入'
	WHERE "TranNo"='L5501';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L5052連動進入'
	WHERE "TranNo"='L5502';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L5053連動進入'
	WHERE "TranNo"='L5503';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L5054連動進入'
	WHERE "TranNo"='L5504';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L5051或L5052連動進入'
	WHERE "TranNo"='L5505';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L5056連動進入'
	WHERE "TranNo"='L5506';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L5053連動進入'
	WHERE "TranNo"='L5507';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L5060案件處理清單]進入'
	WHERE "TranNo"='L5601';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L5060案件處理清單]進入'
	WHERE "TranNo"='L5602';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L5060案件處理清單]進入'
	WHERE "TranNo"='L5603';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L5060案件處理清單]進入'
	WHERE "TranNo"='L5604';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L5060案件處理清單]進入'
	WHERE "TranNo"='L5605';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L5062法務催收人員查詢]進入'
	WHERE "TranNo"='L5606';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L5060案件處理清單]進入'
	WHERE "TranNo"='L5607';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L5071債權案件明細查詢]進入'
	WHERE "TranNo"='L5701';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L5074債務協商作業－應處理事項清單]進入'
	WHERE "TranNo"='L5702';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L5974債權銀行帳號明細資料查詢]進入'
	WHERE "TranNo"='L5703';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L5073債務協商作業-撥付日期查詢]進入'
	WHERE "TranNo"='L5704';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L5971債務協商交易資料查詢]進入'
	WHERE "TranNo"='L5711';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L5074債務協商作業－應處理事項清單]進入'
	WHERE "TranNo"='L5712';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L5982 國稅局申報檔查詢]進入'
	WHERE "TranNo"='L5812';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L5022進入'
	WHERE "TranNo"='L5914';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L5060案件處理清單]進入'
	WHERE "TranNo"='L5960';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L5060案件處理清單]進入'
	WHERE "TranNo"='L5961';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L5060案件處理清單]進入'
	WHERE "TranNo"='L5962';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L5060案件處理清單]進入'
	WHERE "TranNo"='L5963';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L5060案件處理清單]進入'
	WHERE "TranNo"='L5964';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L5060案件處理清單]進入'
	WHERE "TranNo"='L5965';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L5071債權案件明細查詢]進入'
	WHERE "TranNo"='L5976';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L5080建商名單查詢]進入'
	WHERE "TranNo"='L5983';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L6064進入'
	WHERE "TranNo"='L6069';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L6022企金費用代碼查詢]進入'
	WHERE "TranNo"='L6202';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L6023進入'
	WHERE "TranNo"='L6203';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L6024進入'
	WHERE "TranNo"='L6204';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L6025進入'
	WHERE "TranNo"='L6205';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L6031 指標利率種類查詢]進入'
	WHERE "TranNo"='L6301';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L6032 指標利率資料查詢]進入'
	WHERE "TranNo"='L6302';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L6030 特殊/例假日查詢]進入'
	WHERE "TranNo"='L6310';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L6041 使用者資料查詢]進入'
	WHERE "TranNo"='L6401';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L6042 交易控制檔查詢]進入'
	WHERE "TranNo"='L6402';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L6043 權限群組查詢]進入'
	WHERE "TranNo"='L6403';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L6052 會計變動數值查詢]進入'
	WHERE "TranNo"='L6502';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L6061 會計科子細目查詢]進入'
	WHERE "TranNo"='L6601';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L6062 行業別代號查詢]進入'
	WHERE "TranNo"='L6602';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L6063 擔保品代號資料查詢]進入'
	WHERE "TranNo"='L6603';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L6064 各類代碼檔]進入'
	WHERE "TranNo"='L6604';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L6065 逾期新增減少原因]進入'
	WHERE "TranNo"='L6605';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L6066 主管理由查詢]進入'
	WHERE "TranNo"='L6606';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L6067 保證人關係代碼查詢]進入'
	WHERE "TranNo"='L6607';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L6068  報表代號對照檔]連動進入'
	WHERE "TranNo"='L6608';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L6070進入'
	WHERE "TranNo"='L6700';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L6071 行庫資料查詢]進入'
	WHERE "TranNo"='L6701';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L6072 營業單位對照檔查詢]進入'
	WHERE "TranNo"='L6702';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L6073 保險/鑑定公司資料查詢]進入'
	WHERE "TranNo"='L6703';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L6074 地區別資料查詢]進入'
	WHERE "TranNo"='L6704';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L6075 聯徵報送-地區別資料查詢]進入'
	WHERE "TranNo"='L6705';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L6077 現金流量預估資料查詢]進入'
	WHERE "TranNo"='L6707';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L6078 利息收入預算數查詢]進入'
	WHERE "TranNo"='L6708';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L6079 帳冊別目標金額查詢]進入'
	WHERE "TranNo"='L6709';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L6081 介紹人加碼獎勵津貼標準設定數查詢]進入'
	WHERE "TranNo"='L6751';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L6082 放款業績工作月查詢]進入'
	WHERE "TranNo"='L6752';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L6083 房貸專員所屬業務部室]進入'
	WHERE "TranNo"='L6753';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L6084 業績件數及金額核算標準查詢]進入'
	WHERE "TranNo"='L6754';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L6085 單位及主管代號查詢]進入'
	WHERE "TranNo"='L6755';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易'
	WHERE "TranNo"='L6756';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易[L6084 業績件數及金額核算標準查詢]進入'
	WHERE "TranNo"='L6757';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易[L6087 協辦獎勵津貼標準查詢]進入'
	WHERE "TranNo"='L6787';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易[L6089 團康獎勵津貼標準設定查詢]進入'
	WHERE "TranNo"='L6789';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易'
	WHERE "TranNo"='L6901';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L6907未銷帳餘額明細查詢]進入'
	WHERE "TranNo"='L6908';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='本交易為連動交易，請從交易[L6932 資料變更交易查詢]進入'
	WHERE "TranNo"='L6933';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='本交易為連動交易，請從交易[L6933 資料變更明細查詢]進入'
	WHERE "TranNo"='L6934';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L6001進入'
	WHERE "TranNo"='L6981';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L6001進入'
	WHERE "TranNo"='L6984';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L6001進入'
	WHERE "TranNo"='L6985';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L6001進入'
	WHERE "TranNo"='L6989';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L6084進入'
	WHERE "TranNo"='L6994';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L7022違約損失率檔查詢]進入'
	WHERE "TranNo"='L7202';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L7904特殊客觀減損狀況查詢]進入'
	WHERE "TranNo"='L7204';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L7903商品分類資料查詢]進入'
	WHERE "TranNo"='L7210';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8031';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8032';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8033';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8034';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8035';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8036';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8037';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8038';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8039';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8040';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8041';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8042';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8043';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8044';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8045';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8046';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8047';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8048';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8049';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8050';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8051';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8052';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8053';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8054';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8055';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8056';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8057';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8058';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8059';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8060';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8061';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8062';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8063';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8064';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8065';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8066';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030連動進入'
	WHERE "TranNo"='L8067';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L8081/L8082/L8083進入'
	WHERE "TranNo"='L8084';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：L8080進入'
	WHERE "TranNo"='L8100';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L8081 AML定審高風險資料查詢]、[L8082. AML定審中風險資料查詢]、[L8083. AML定審低風險'資料查詢]進入
	WHERE "TranNo"='L8101';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L8922 疑似洗錢交易合理性查詢]進入'
	WHERE "TranNo"='L8203';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L8923 疑似洗錢交易訪談記錄查詢]進入'
	WHERE "TranNo"='L8204';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L8922 疑似洗錢交易合理性查詢、L8923 疑似洗錢訪談交易記錄查詢]進入'
	WHERE "TranNo"='L8205';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic040連動進入'
	WHERE "TranNo"='L8301';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic041連動進入'
	WHERE "TranNo"='L8302';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic042連動進入'
	WHERE "TranNo"='L8303';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic575連動進入'
	WHERE "TranNo"='L8304';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic044連動進入'
	WHERE "TranNo"='L8305';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic045連動進入'
	WHERE "TranNo"='L8306';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic046連動進入'
	WHERE "TranNo"='L8307';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic047連動進入'
	WHERE "TranNo"='L8308';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic048連動進入'
	WHERE "TranNo"='L8309';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic049連動進入'
	WHERE "TranNo"='L8310';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic050連動進入'
	WHERE "TranNo"='L8311';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic051連動進入'
	WHERE "TranNo"='L8312';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic52連動進入'
	WHERE "TranNo"='L8313';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic53連動進入'
	WHERE "TranNo"='L8314';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic54連動進入'
	WHERE "TranNo"='L8315';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic055連動進入'
	WHERE "TranNo"='L8316';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic56連動進入'
	WHERE "TranNo"='L8317';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic060連動進入'
	WHERE "TranNo"='L8318';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic061連動進入'
	WHERE "TranNo"='L8319';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic062連動進入'
	WHERE "TranNo"='L8320';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic063連動進入'
	WHERE "TranNo"='L8321';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic440連動進入'
	WHERE "TranNo"='L8322';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic442連動進入'
	WHERE "TranNo"='L8323';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic443連動進入'
	WHERE "TranNo"='L8324';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic444連動進入'
	WHERE "TranNo"='L8325';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic446連動進入'
	WHERE "TranNo"='L8326';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic447連動進入'
	WHERE "TranNo"='L8327';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic448連動進入'
	WHERE "TranNo"='L8328';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic575連動進入'
	WHERE "TranNo"='L8329';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic451連動進入'
	WHERE "TranNo"='L8330';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic454連動進入'
	WHERE "TranNo"='L8331';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic570連動進入'
	WHERE "TranNo"='L8332';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic571連動進入'
	WHERE "TranNo"='L8333';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic572連動進入'
	WHERE "TranNo"='L8334';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic573連動進入'
	WHERE "TranNo"='L8335';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic574連動進入'
	WHERE "TranNo"='L8336';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8030-Jcic575連動進入'
	WHERE "TranNo"='L8337';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易L8924連動進入'
	WHERE "TranNo"='L8925';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L8922 疑似洗錢交易合理性查詢]進入'
	WHERE "TranNo"='L8926';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從交易：[L9911 會計部核定備抵損失查詢]進入'
	WHERE "TranNo"='L9111';
    UPDATE "TxTranCode"
    SET "ChainTranMsg"='此為連動交易，請從入口交易進入'
    WHERE "TranNo"='LC014';
