
package com.st1.sklwebservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsSKL_Authentication", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/C:/SKL/test/ad.wsdl")
public class WsSKLAuthentication
    extends Service
{

    private final static URL WSSKLAUTHENTICATION_WSDL_LOCATION;
    private final static WebServiceException WSSKLAUTHENTICATION_EXCEPTION;
    private final static QName WSSKLAUTHENTICATION_QNAME = new QName("http://tempuri.org/", "wsSKL_Authentication");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/SKL/test/ad.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSSKLAUTHENTICATION_WSDL_LOCATION = url;
        WSSKLAUTHENTICATION_EXCEPTION = e;
    }

    public WsSKLAuthentication() {
        super(__getWsdlLocation(), WSSKLAUTHENTICATION_QNAME);
    }

    public WsSKLAuthentication(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSSKLAUTHENTICATION_QNAME, features);
    }

    public WsSKLAuthentication(URL wsdlLocation) {
        super(wsdlLocation, WSSKLAUTHENTICATION_QNAME);
    }

    public WsSKLAuthentication(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSSKLAUTHENTICATION_QNAME, features);
    }

    public WsSKLAuthentication(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsSKLAuthentication(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsSKLAuthenticationSoap
     */
    @WebEndpoint(name = "wsSKL_AuthenticationSoap")
    public WsSKLAuthenticationSoap getWsSKLAuthenticationSoap() {
        return super.getPort(new QName("http://tempuri.org/", "wsSKL_AuthenticationSoap"), WsSKLAuthenticationSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsSKLAuthenticationSoap
     */
    @WebEndpoint(name = "wsSKL_AuthenticationSoap")
    public WsSKLAuthenticationSoap getWsSKLAuthenticationSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "wsSKL_AuthenticationSoap"), WsSKLAuthenticationSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns WsSKLAuthenticationSoap
     */
    @WebEndpoint(name = "wsSKL_AuthenticationSoap12")
    public WsSKLAuthenticationSoap getWsSKLAuthenticationSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "wsSKL_AuthenticationSoap12"), WsSKLAuthenticationSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsSKLAuthenticationSoap
     */
    @WebEndpoint(name = "wsSKL_AuthenticationSoap12")
    public WsSKLAuthenticationSoap getWsSKLAuthenticationSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "wsSKL_AuthenticationSoap12"), WsSKLAuthenticationSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSSKLAUTHENTICATION_EXCEPTION!= null) {
            throw WSSKLAUTHENTICATION_EXCEPTION;
        }
        return WSSKLAUTHENTICATION_WSDL_LOCATION;
    }

}
