
package com.st1.sklwebservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "wsSKL_AuthenticationSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsSKLAuthenticationSoap {


    /**
     * 
     * @param password
     * @param strAuthType
     * @param account
     * @return
     *     returns com.st1.sklwebservice.IsAuthenticatedResponse.IsAuthenticatedResult
     */
    @WebMethod(operationName = "IsAuthenticated", action = "http://tempuri.org/IsAuthenticated")
    @WebResult(name = "IsAuthenticatedResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IsAuthenticated", targetNamespace = "http://tempuri.org/", className = "com.st1.sklwebservice.IsAuthenticated")
    @ResponseWrapper(localName = "IsAuthenticatedResponse", targetNamespace = "http://tempuri.org/", className = "com.st1.sklwebservice.IsAuthenticatedResponse")
    public com.st1.sklwebservice.IsAuthenticatedResponse.IsAuthenticatedResult isAuthenticated(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "strAuthType", targetNamespace = "http://tempuri.org/")
        String strAuthType);

    /**
     * 
     * @param password
     * @param account
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "AD_IsAuthenticated", action = "http://tempuri.org/AD_IsAuthenticated")
    @WebResult(name = "AD_IsAuthenticatedResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AD_IsAuthenticated", targetNamespace = "http://tempuri.org/", className = "com.st1.sklwebservice.ADIsAuthenticated")
    @ResponseWrapper(localName = "AD_IsAuthenticatedResponse", targetNamespace = "http://tempuri.org/", className = "com.st1.sklwebservice.ADIsAuthenticatedResponse")
    public boolean adIsAuthenticated(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param password
     * @param account
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "Intranet_IsAuthenticated", action = "http://tempuri.org/Intranet_IsAuthenticated")
    @WebResult(name = "Intranet_IsAuthenticatedResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Intranet_IsAuthenticated", targetNamespace = "http://tempuri.org/", className = "com.st1.sklwebservice.IntranetIsAuthenticated")
    @ResponseWrapper(localName = "Intranet_IsAuthenticatedResponse", targetNamespace = "http://tempuri.org/", className = "com.st1.sklwebservice.IntranetIsAuthenticatedResponse")
    public boolean intranetIsAuthenticated(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param password
     * @param strAuthType
     * @param account
     * @return
     *     returns com.st1.sklwebservice.IntraAuthenticated
     */
    @WebMethod(operationName = "IsAuthenticatedClass", action = "http://tempuri.org/IsAuthenticatedClass")
    @WebResult(name = "IsAuthenticatedClassResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IsAuthenticatedClass", targetNamespace = "http://tempuri.org/", className = "com.st1.sklwebservice.IsAuthenticatedClass")
    @ResponseWrapper(localName = "IsAuthenticatedClassResponse", targetNamespace = "http://tempuri.org/", className = "com.st1.sklwebservice.IsAuthenticatedClassResponse")
    public IntraAuthenticated isAuthenticatedClass(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "strAuthType", targetNamespace = "http://tempuri.org/")
        String strAuthType);

}
