-- 2021-10-08 智偉修改
ALTER TABLE "PfCoOfficer" MODIFY "AreaItem" NVARCHAR2(20) NOT NULL;
ALTER TABLE "PfCoOfficer" MODIFY "DistItem" NVARCHAR2(20) NOT NULL;
ALTER TABLE "PfCoOfficer" MODIFY "DeptItem" NVARCHAR2(20) NOT NULL;